# Generated by Django 5.2.6 on 2025-12-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0003_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="council_images/"),
        ),
    ]
