# Generated by Django 5.2.6 on 2025-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0004_council_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="council",
            name="image",
        ),
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
